<template>
    <div>
        <video ref="localVideo" id="localVideo" autoplay muted></video>
        <button @click="startStreaming">Start Streaming</button>
    </div>
</template>

<script>
import axios from "axios";

export default {
    data() {
        return {
            localStream: null,
            peerConnection: null,
            dataChannel: null,
        };
    },
    methods: {
        startStreaming() {
            navigator.mediaDevices
                .getUserMedia({video: true, audio: true})
                .then((stream) => {
                    this.localStream = stream;
                    this.$refs.localVideo.srcObject = stream;

                    this.peerConnection = new RTCPeerConnection();
                    this.peerConnection.addStream(stream);

                    this.dataChannel = this.peerConnection.createDataChannel("myDataChannel");
                    this.dataChannel.onopen = this.handleDataChannelOpen;
                    this.dataChannel.onmessage = this.handleDataChannelMessage;


                    // An offer is a description of a media session that the sender would like to establish with another peer. It contains information such as the type of media that will be shared (e.g. video and audio), codecs, and other relevant details. An offer is created using the RTCPeerConnection.createOffer method and is set as the local description using the RTCPeerConnection.setLocalDescription method.
                    this.peerConnection
                        .createOffer()
                        .then((offer) => this.peerConnection.setLocalDescription(offer))
                        .then(() => {
                            // send the offer to a server to be forwarded to the other peer
                            axios.post("/offer", {
                                offer: this.peerConnection.localDescription,
                            });
                        });

                    // A candidate is a potential network address that a peer can use to communicate with another peer. It contains information such as the IP address, port, and transport protocol. Candidates are generated by the browser and are sent to the other peer as part of the connection establishment process. They are sent using the RTCPeerConnection.onicecandidate event and the event.candidate property.
                    this.peerConnection.onicecandidate = (event) => {
                        if (event.candidate) {
                            // send the candidate to a server to be forwarded to the other peer
                            axios.post("/candidate", {
                                candidate: event.candidate,
                            });
                        }
                    };
                })
                .catch((error) => {
                    console.error(error);
                });
        },
        handleDataChannelOpen(event) {
            console.log("Data channel is open and ready to be used.", event);
        },
        handleDataChannelMessage(event) {
            console.log("Data channel message received.", event.data);
        },
    },
};
</script>
